## Numerical Python (NumPy)

In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3]

x = np.array(my_list)
x

array([1, 2, 3])

In [4]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [5]:
m = np.array([x, y])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
m.shape

(2, 3)

In [7]:
# Create a list starting at 0, ending at 30, counting up by 2.
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [8]:
# Reshape list into 3 x 5 matrix.
n.reshape(3, 5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [9]:
# Create a list starting at 0, ending at 4, containing 9 evenly spaced values.
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [10]:
# Changes the shape and size of a list in place.
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [11]:
# Creates a matrix of 1s, given a tuple of dimensions.
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Creates a matrix of 0s, given a tuple of dimensions.
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# Creates an identity matrix.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Extracts a diagonal or creates a diagonal array.
np.diag(o)

array([0., 2., 4.])

In [15]:
# Repeating elements of an array.
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [16]:
# Combining arrays.
p = np.ones((2, 3), int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
# Stack arrays in sequence vertically.
np.vstack([p, p * 2])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [18]:
# Stack arrays in sequence horizontally.
np.hstack([p, p * 2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Dot Product

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [19]:
# (1 * 4) + (2 * 5) + (3 * 6) = 32
v = x.dot(y)
v

32

In [24]:
z = np.array([y, y ** 2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [25]:
z.shape

(2, 3)

In [22]:
# Get the transposition.
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [26]:
# Get the data type of the matrix.
z.dtype

dtype('int64')

In [28]:
# Cast the matrix to a given data type.
z = z.astype('f')
z

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)